name: Sync Specific Odoo Module

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: 'Odoo module name'
        required: true

# Prevent multiple workflow runs from pushing at same time
concurrency:
  group: sync-module
  cancel-in-progress: false

jobs:
  sync-module:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout deploy repo
      - name: Checkout Deploy Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # 2. Sync latest remote main
      - name: Sync with Remote Main
        run: |
          git fetch origin main
          git reset --hard origin/main

      # 3. Clone developer repo
      - name: Clone Developer Repo
        run: |
          git clone https://github.com/Raghavendra-prixgen/new-test-.git upstream

      # 4. Verify module exists
      - name: Verify Module Exists
        run: |
          if [ ! -d "upstream/${{ github.event.inputs.module_name }}" ]; then
            echo "Module does not exist!"
            exit 1
          fi

      # 5. Copy selected module
      - name: Copy Selected Module
        run: |
          rm -rf ${{ github.event.inputs.module_name }}
          cp -r upstream/${{ github.event.inputs.module_name }} ./

      # 6. Cleanup upstream repo
      - name: Remove Upstream Repo
        run: |
          rm -rf upstream

      # 7. Commit changes
      - name: Commit Changes
        run: |
          git config user.name "Raghavendra-prixgen"
          git config user.email "raghavendra.krishnamurthy@prixgen.com"

          git add ${{ github.event.inputs.module_name }}

          git commit -m "Updated module: ${{ github.event.inputs.module_name }}" || echo "No changes to commit"

      # 8. Safe push
      - name: Push Changes
        run: |
          git pull --rebase origin main
          git push origin main