name: Sync Specific Odoo Module

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: 'Odoo module name'
        required: true

jobs:
  sync-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Deploy Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Clone Developer Repo
        run: |
          git clone https://github.com/Raghavendra-prixgen/new-test-.git upstream

      - name: Copy Selected Module
        run: |
          rm -rf ${{ github.event.inputs.module_name }}
          cp -r upstream/${{ github.event.inputs.module_name }} ./

      - name: Remove Upstream Repo
        run: |
          rm -rf upstream

      - name: Commit Changes
        run: |
          git config user.name "Raghavendra-prixgen"
          git config user.email "raghavendra.krishnamurthy@prixgen.com"

          git add .

          git commit -m "Updated module: ${{ github.event.inputs.module_name }}" || echo "No changes"

      - name: Pull Latest Changes
        run: |
          git pull origin main --rebase

      - name: Push Changes
        run: |
          git push origin main --force